ALTER TABLE users ADD COLUMN tier VARCHAR(20) NOT NULL DEFAULT 'free';
ALTER TABLE users ADD COLUMN ai_credits_remaining INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN credits_reset_at TIMESTAMPTZ;
